# Generated by Django 5.2.3 on 2025-08-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Drive Name')),
                ('route', models.CharField(blank=True, max_length=200, null=True, verbose_name='Route')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price Per Hour')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/cars', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
